# Generated by Django 4.2.2 on 2025-07-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Введите Ваше имя",
                max_length=120,
                null=True,
                verbose_name="Имя пользователя",
            ),
        ),
    ]
