# Generated by Django 5.2.1 on 2025-07-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"verbose_name": "Блог", "verbose_name_plural": "Посты"},
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/image",
                verbose_name="Превью (изображение)",
            ),
        ),
    ]
