# Generated by Django 4.2.2 on 2025-07-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_options_alter_blogpost_preview_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "permissions": [
                    ("can_edit_post", "Can edit post"),
                    ("can_delete_post", "Can delete post"),
                ],
                "verbose_name": "Блог",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
