# Generated by Django 5.2.1 on 2025-06-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("inn", models.CharField(max_length=20, verbose_name="ИНН")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Контактная информация",
                "verbose_name_plural": "Контактные информации",
            },
        ),
    ]
